# Generated by Django 4.1.7 on 2023-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='Slider name1')),
                ('name2', models.CharField(max_length=60, verbose_name='Slider name2')),
                ('text', models.TextField(verbose_name='Slider text')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Slider image1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Slider image2')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='SliderActive name1')),
                ('name2', models.CharField(max_length=60, verbose_name='SliderActive name2')),
                ('text', models.TextField(verbose_name='SliderActive text')),
                ('img1', models.ImageField(upload_to='images', verbose_name='SliderActive image1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='SliderActive image2')),
            ],
        ),
    ]
