# Generated by Django 4.1.7 on 2023-03-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Sub Category name')),
                ('price', models.PositiveIntegerField(verbose_name='Sub Category price')),
                ('img', models.ImageField(upload_to='images', verbose_name='Sub Category images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categ', to='main.category')),
            ],
        ),
    ]
